### ISSUE TITLE
No guidance on layout

### ISSUE THREAD

**Issue by SnowboardTechie** [learn-co-students/devise_lab-v-000#197]
The walkthrough will not pass without adding content_tags and links to the application layout. This is not mentioned at all in the entire walkthrough and makes completing and understanding it unnecessarily difficult.

**Comment by marielfrank** [comment]
Same. I had to look at someone else's pull request to figure out how to get the content_tags and flash messages set up correctly. Some instructions on this part would really be helpful.

**Comment by lisaychuang** [comment]
This issue is still outstanding - the [Devise lesson](https://learn.co/tracks/full-stack-web-dev-with-react/rails/authentication/devise) notes did provide code snippets for `Flash` messages and link for Sign in & Sign Up, but the lab instruction did not include requirements for updating Layout at all.
